# Generated by Django 4.2.16 on 2024-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("brand_id", models.AutoField(primary_key=True, serialize=False)),
                ("brand_name", models.CharField(max_length=30, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table_comment": "Adding Brand",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                ("color_id", models.AutoField(primary_key=True, serialize=False)),
                ("color_name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table_comment": "Adding Colors",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table_comment": "Adding products",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                ("model_id", models.AutoField(primary_key=True, serialize=False)),
                ("model_name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table_comment": "Add Products Model Number",
                "managed": True,
            },
        ),
    ]
