# Generated by Django 4.2.16 on 2024-12-06 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email_id", models.EmailField(max_length=120, unique=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Admin"), (1, "Staff")], default=1
                    ),
                ),
                ("mobile_number", models.CharField(max_length=15)),
                ("business_name", models.CharField(default="", max_length=40)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "parent_business",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parentBusiness",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table_comment": "users",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TransactionPartner",
            fields=[
                ("partner_id", models.AutoField(primary_key=True, serialize=False)),
                ("partner_name", models.CharField(max_length=50)),
                ("office_number", models.CharField(max_length=30)),
                ("street_address", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("landmark", models.CharField(max_length=50)),
                ("pincode", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=50)),
                ("mobile", models.CharField(max_length=15)),
                ("gst_id", models.CharField(max_length=50, unique=True)),
                (
                    "partner_type",
                    models.IntegerField(
                        choices=[(0, "seller"), (1, "buyer")], default=0
                    ),
                ),
                (
                    "is_registered",
                    models.IntegerField(
                        choices=[(0, "Registered"), (1, "Not Registered")], default=0
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="createdBy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "Adding partners",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Retailer",
            fields=[
                ("retailer_id", models.AutoField(primary_key=True, serialize=False)),
                ("retailer_name", models.CharField(max_length=30)),
                ("mobile", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retailerCreatedBy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table_comment": "Adding retailers",
                "managed": True,
            },
        ),
    ]
