# Generated by Django 4.2.16 on 2024-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyerInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hsncode", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gst_perc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=20)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gst_perc", models.DecimalField(decimal_places=2, max_digits=20)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("inoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "entityType",
                    models.CharField(
                        choices=[
                            ("TransactionPartner", " Transaction Partner"),
                            ("Retailer", "Retailer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gst_Perc", models.DecimalField(decimal_places=2, max_digits=15)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[(0, "Fullfilled"), (1, "Pending"), (2, "Rejected")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SellerInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hsncode", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gst_perc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
