# Generated by Django 4.2.16 on 2024-12-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("product", "0001_initial"),
        ("useradmin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hsncode", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gst_perc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerBrandId",
                        to="product.brand",
                    ),
                ),
                (
                    "color_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerColorId",
                        to="product.color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerCreatedBy",
                        to="useradmin.adminuser",
                    ),
                ),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerModelName",
                        to="product.productmodel",
                    ),
                ),
                (
                    "partner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerPartnerId",
                        to="useradmin.transactionpartner",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sellerProductId",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("inoice_id", models.AutoField(primary_key=True, serialize=False)),
                ("entity_id", models.PositiveIntegerField()),
                (
                    "entityType",
                    models.CharField(
                        choices=[
                            ("TransactionPartner", " Transaction Partner"),
                            ("Retailer", "Retailer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("gst_Perc", models.DecimalField(decimal_places=2, max_digits=15)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                (
                    "payment_status",
                    models.IntegerField(
                        choices=[(0, "Fullfilled"), (1, "Pending"), (2, "Rejected")],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="InvoiceCreatedBy",
                        to="useradmin.adminuser",
                    ),
                ),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=20)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gst_perc", models.DecimalField(decimal_places=2, max_digits=20)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventoryBrandId",
                        to="product.brand",
                    ),
                ),
                (
                    "color_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventoryColorId",
                        to="product.color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="InventoryCreatedBy",
                        to="useradmin.adminuser",
                    ),
                ),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventoryModelName",
                        to="product.productmodel",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventoryProductId",
                        to="product.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BuyerInventory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hsncode", models.CharField(max_length=50)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gross_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("discount_perc", models.DecimalField(decimal_places=2, max_digits=3)),
                ("net_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("gst_perc", models.DecimalField(decimal_places=2, max_digits=10)),
                ("final_amount", models.DecimalField(decimal_places=2, max_digits=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyerBrandId",
                        to="product.brand",
                    ),
                ),
                (
                    "color_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyerColorId",
                        to="product.color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyerCreatedBy",
                        to="useradmin.adminuser",
                    ),
                ),
                (
                    "model_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyerModelName",
                        to="product.productmodel",
                    ),
                ),
                (
                    "partner_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyerPartnerId",
                        to="useradmin.transactionpartner",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyerProductId",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
