# Generated by Django 4.2.16 on 2024-12-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerinventory",
            name="brand_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sellerBrandId",
                to="product.brand",
            ),
        ),
        migrations.AddField(
            model_name="sellerinventory",
            name="color_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sellerColorId",
                to="product.color",
            ),
        ),
    ]
