# Generated by Django 4.2.16 on 2024-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="inoice_id",
            new_name="invoice_id",
        ),
    ]
