# Generated by Django 4.2.16 on 2024-12-20 04:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_rename_inoice_id_invoice_invoice_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="buyerinventory",
            old_name="model_name",
            new_name="model_id",
        ),
        migrations.RenameField(
            model_name="inventory",
            old_name="model_name",
            new_name="model_id",
        ),
        migrations.RenameField(
            model_name="sellerinventory",
            old_name="model_name",
            new_name="model_id",
        ),
    ]
